### ISSUE TITLE
Question about  Interval division of int or float data

### ISSUE THREAD

**Issue by Dingyue96** [davidfoerster/schema-matching#2]
Hello, David. 
I am learning this schema-matching method. In this method, in order to calculate the distance matrix of two columns of data, some calculation of specific values is required, such as ItemLetterAverage, LetterVariationCoefficien, LetterProbablility, ItemAverage, ItemProbability, etc.
When a column data type is int or float, to evaluate the difference between values, it is necessary to divide the data with equal intervals, and how is the number of intervals and steps determined? Can I get more documentation about this code? Looking forward to your reply.

**Comment by davidfoerster** [comment]
This piece of software is a slightly cleaned-up version of a university course project, so there’s no more documentation than what you can find in the repository.

What do you mean "divide the data with equal intervals"? The difference between numeric values is determined by subtraction (duh). There is no check that the probability distribution of value occurrence is auto-correlated or anything.

Lastly, this is a programming issue tracker and no help desk. If you have any question about the workings and use of the software please write me an e-mail. The address given in the commit headers will do fine.
