### ISSUE TITLE
request more detailed  readme document

### ISSUE THREAD

**Issue by chenjintaozju** [davidfoerster/schema-matching#4]
I'm learning schema-matching currently,and I download your project.But I can understand it very well.Can you write a more detailed document?Thanks!

**Comment by davidfoerster** [comment]
Quoting from #2:

> This piece of software is a slightly cleaned-up version of a university course project, so there’s no more documentation than what you can find in the repository.

I'm open to fix (documentation) errors but I don't intend to provide more than what's here. I'm aware that my project is no good teaching material and it isn't meant to be one.

Nonetheless I made some minor improvements to `README.md`, the command-line help, and the self-explanation of verbose output in 8569b00830dd4bbffe390344509c358eea5eb27e and 5edfde4d1962d35a3354fc12b13eb1205a1fec25.

If you have more concrete questions regarding usage or understanding, I’ll try to answer them as time permits.

**Comment by chenjintaozju** [comment]
I understand,thank you!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"David Foerster"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月19日(星期六) 凌晨0:52
收件人:&nbsp;"davidfoerster/schema-matching"<schema-matching@noreply.github.com&gt;;
抄送:&nbsp;"星沉"<1285098441@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [davidfoerster/schema-matching] request more detailed  readme document (#4)




Quoting from #2:
  
This piece of software is a slightly cleaned-up version of a university course project, so there’s no more documentation than what you can find in the repository.
  
I'm open to fix (documentation) errors but I don't intend to provide more than what's here. I'm aware that my project is no good teaching material and it isn't meant to be one.
 
Nonetheless I made some minor improvements to README.md, the command-line help, and the self-explanation of verbose output in 5edfde4.
